/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package assignment1;

// import assignment1.task1.Hello;
// import assignment1.task2.Time;
// import assignment1.task3.Nine;
// import assignment1.task4.DangerousWork;
// import assignment1.task5.Diamonds;
// import assignment1.task6.GameSRP;
// import assignment1.task7.DayOfWeek;
// import assignment1.task8.Ants;
// import assignment1.task9.Hex2Dec;
// import assignment1.task10.PrintCalendar;


/**
 * This is the main method to start all of the small tasks.
 */
public class App {
  /**
   * The program starting point.
   *
   * @param args Unused program arguments.
   */
  public static void main(String[] args) {
  

    // Hello hello = new Hello();
    // hello.run();

    // Time time = new Time();
    // time.run(scan);

    // Nine nine = new Nine();
    // nine.run();

    // DangerousWork dangerousWork = new DangerousWork();
    // dangerousWork.run();

    // Diamonds diamonds = new Diamonds();
    // diamonds.run();

    // GameSRP game = new GameSRP();
    // game.run();

    // DayOfWeek dayOfWeek = new DayOfWeek();
    // dayOfWeek.run();
    
    // Ants ants = new Ants();
    // ants.run();
    
    // Hex2Dec hex2Dec = new Hex2Dec();
    // hex2Dec.run();

    // PrintCalendar printCalendar = new PrintCalendar();
    // printCalendar.run();

   
    System.exit(0);
  }
}
